version: '3.9'

services:

  mysqldb:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: promotion
