spring:
  datasource:
    url: jdbc:mysql://promotion.czqfz3juqgyi.eu-west-2.rds.amazonaws.com:3306/promotion?user=admin&password=promotionPass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        generate_statistics: false

cloud:
  aws:
    credentials:
      access-key: AKIASZ66QDRUNLTXDRUJ
      secret-key: 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
    region:
      static: eu-west-2
    stack:
      auto: false

application:
  bucket:
    name: smbr-promotion/course

jwt:
  secret: promotion
