spring:
  datasource:
    url: jdbc:mysql://localhost:3306/promotion?user=root&password=root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        generate_statistics: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  flyway:
    locations: classpath:db/migration/
    baseline-on-migrate: true
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    enabled: true
    placeholder-replacement: false
    table: schema_version
    schemas: promotion
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: AKIASZ66QDRUNLTXDRUJ
      secret-key: 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
    region:
      static: eu-west-2
    stack:
      auto: false

application:
  bucket:
    name: smbr-promotion/course

jwt:
  secret: promotion

system:
  default:
    pass-course-threshold-value: 8
